### ISSUE TITLE
[스타일링] 로그인 페이지 마크업 스타일링

### ISSUE THREAD

**Issue by jin123457** [Sol-Yong/instagram-clone-client#5]
인스타그램 클론코딩 시작

**Comment by Yongveloper** [comment]
솔아 styled components 설치하고 사용하기 전에
global style에 reset css 적용하고 작업해주라 
기본적으로 html 태그들에 적용되어있는 css 값들이 있어서 다 초기화 하고 깔끔한 상태에서 스타일링 하는 게 더 편할 거야

참고 링크 줄게!
1. https://www.npmjs.com/package/styled-reset
2. https://www.howdy-mj.me/css/styled-components-with-global-style/
3. https://github.com/Yongveloper/LOL-MBTI/blob/main/styles/GlobalStyle.ts
